(in-package :machine-description)

;; Errors during JSON parsing
(define-condition json-parsing-error (error)
  ()
  (:documentation "Error when JSON parsing fails"))


;; Errors during retrieving of raw values
(define-condition invalid-json (error)
  ()
  (:documentation "Error when JSON is unfit for machine description"))

;; Errors during processing of raw values (type checking)
(define-condition invalid-json-name (invalid-json)
  ()
  (:documentation "Error for invalid name"))
(define-condition invalid-json-alphabet (invalid-json)
  ()
  (:documentation "Error for invalid alphabet"))
(define-condition invalid-json-blank (invalid-json)
  ()
  (:documentation "Error for invalid blank"))
(define-condition invalid-json-states (invalid-json)
  ()
  (:documentation "Error for invalid states"))
(define-condition invalid-json-initial-state (invalid-json)
  ()
  (:documentation "Error for invalid initial state"))
(define-condition invalid-json-finals (invalid-json)
  ()
  (:documentation "Error for invalid final states"))
(define-condition invalid-json-transitions (invalid-json)
  ()
  (:documentation "Error for invalid transitions"))
(define-condition invalid-json-transition (invalid-json-transitions)
  ()
  (:documentation "Error for one invalid transition (for instance with invalid TR fields)"))


(define-condition invalid-json-missing-name (invalid-json)
  ()
  (:documentation "Error when parsed JSON lacks field name")
  (:report (lambda (condition stream)
			 (format stream "JSON object lacks a \"name\" field"))))
(define-condition invalid-json-missing-alphabet (invalid-json)
  ()
  (:documentation "Error when parsed JSON lacks field alphabet")
  (:report (lambda (condition stream)
			 (format stream "JSON object lacks an \"alphabet\" field"))))
(define-condition invalid-json-missing-blank (invalid-json)
  ()
  (:documentation "Error when parsed JSON lacks field blank")
  (:report (lambda (condition stream)
			 (format stream "Machine description lacks a \"blank\" field"))))
(define-condition invalid-json-missing-states (invalid-json)
  ()
  (:documentation "Error when parsed JSON lacks field states")
  (:report (lambda (condition stream)
			 (format stream "Machine description lacks a \"states\" field"))))
(define-condition invalid-json-missing-initial-state (invalid-json)
  ()
  (:documentation "Error when parsed JSON lacks field initial")
  (:report (lambda (condition stream)
			 (format stream "Machine description lacks a \"initial-state\" field"))))
(define-condition invalid-json-missing-finals (invalid-json)
  ()
  (:documentation "Error when parsed JSON lacks field finals")
  (:report (lambda (condition stream)
			 (format stream "Machine description lacks a \"finals\" field"))))
(define-condition invalid-json-missing-transitions (invalid-json)
  ()
  (:documentation "Error when parsed JSON lacks field transitions")
  (:report (lambda (condition stream)
			 (format stream "Machine description lacks a \"transitions\" field"))))

;; Those will be under an invalid-json-transition
(define-condition invalid-json-missing-from-char (invalid-json-transition)
  ()
  (:documentation "Error when a transition has no from-char field"))
(define-condition invalid-json-missing-to-state (invalid-json-transition)
  ()
  (:documentation "Error when a transition has no to-state field"))
(define-condition invalid-json-missing-to-char (invalid-json-transition)
  ()
  (:documentation "Error when a transition has no to-char field"))
(define-condition invalid-json-missing-action (invalid-json-transition)
  ()
  (:documentation "Error when a transition has no action field"))

(define-condition invalid-json-from-state (invalid-json-transition)
  ()
  (:documentation "Error when a transition has an invalid from-state"))
(define-condition invalid-json-from-char (invalid-json-transition)
  ()
  (:documentation "Error when a transition has an invalid from-char"))
(define-condition invalid-json-to-state (invalid-json-transition)
  ()
  (:documentation "Error when a transition has an invalid to-state"))
(define-condition invalid-json-to-char (invalid-json-transition)
  ()
  (:documentation "Error when a transition has an invalid to-char"))
(define-condition invalid-json-action (invalid-json-transition)
  ()
  (:documentation "Error when a transition has an invalid action"))

;; Errors during instantiation of machine description
(define-condition invalid-machine-description-args (error)
  ()
  (:documentation "Error when arguments for machine-description are inconsistent"))
(define-condition invalid-machine-description-name (invalid-machine-description-args)
  ()
  (:documentation "Error when trying to instantiate machine-description with invalid name"))
(define-condition invalid-machine-description-alphabet (invalid-machine-description-args)
  ()
  (:documentation "Error when trying to instantiate machine-description with invalid alphabet"))
(define-condition invalid-machine-description-blank (invalid-machine-description-args)
  ()
  (:documentation "Error when trying to instantiate machine-description with invalid blank"))
(define-condition invalid-machine-description-states (invalid-machine-description-args)
  ()
  (:documentation "Error when trying to instantiate machine-description with invalid states"))
(define-condition invalid-machine-description-initial-state (invalid-machine-description-args)
  ()
  (:documentation "Error when trying to instantiate machine-description with invalid initial state"))
(define-condition invalid-machine-description-finals (invalid-machine-description-args)
  ()
  (:documentation "Error when trying to instantiate machine-description with invalid finals"))
(define-condition invalid-machine-description-transitions (invalid-machine-description-args)
  ()
  (:documentation "Error when trying to instantiate machine-description with invalid transitions"))

;; For transition-result errors:
(define-condition invalid-transition-result-args (error)
  ()
  (:documentation "Error when trying to instantiate a transition-result with invalid args"))
(define-condition invalid-transition-result-to-state (invalid-transition-result-args)
  ()
  (:documentation "Error when trying to instantiate a transition-result with an invalid to-state"))
(define-condition invalid-transition-result-to-char (invalid-transition-result-args)
  ()
  (:documentation "Error when trying to instantiate a transition-result with an invalid to-char"))
(define-condition invalid-transition-result-action (invalid-transition-result-args)
  ()
  (:documentation "Error when trying to instantiate a transition-result with an invalid action"))
